language: go

go:
  - 1.2
  - 1.3

#specify the build_image
build_image: shippableimages/ubuntu1204_go

before_install:
  - source $HOME/.gvm/scripts/gvm;
  - if [[ $SHIPPABLE_GO_VERSION == "tip" ]]; then gvm install tip; gvm use tip; fi
  - if [[ $SHIPPABLE_GO_VERSION == *release* ]]; then gvm install release; gvm use release; fi
  - if [[ $SHIPPABLE_GO_VERSION =~ [0-9].[0-9] ]]; then gvm install go$SHIPPABLE_GO_VERSION; gvm use go$SHIPPABLE_GO_VERSION; fi
  - export GOPATH=$SHIPPABLE_GOPATH

  - go get github.com/t-yuki/gocover-cobertura
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get code.google.com/p/go.tools/cmd/cover

install:
  - go get -d -v ./... && go build -v ./...

script:
    - go build .
#  - go test -coverprofile=coverage.txt -covermode count ./
#  - $GOPATH/bin/gocover-cobertura < coverage.txt > shippable/codecoverage/coverage.xml